version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "tea_db"
      POSTGRES_USER: "tea_db"
      POSTGRES_PASSWORD: "tea_db"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:

      - tea_db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  tst:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "tst_db"
      POSTGRES_USER: "tst_db"
      POSTGRES_PASSWORD: "tst_db"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:

      - tst_db-data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
volumes:
  tea_db-data:
  tst_db-data: