"""add Type model for Tea types 3

Revision ID: 01f0ed020484
Revises: 4eb1764af4be
Create Date: 2024-10-17 17:16:58.810990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01f0ed020484'
down_revision: Union[str, None] = '4eb1764af4be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tea', ['id'])
    op.drop_constraint('tea_type_name_key', 'tea_type', type_='unique')
    op.create_unique_constraint(None, 'tea_type', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tea_type', type_='unique')
    op.create_unique_constraint('tea_type_name_key', 'tea_type', ['name'])
    op.drop_constraint(None, 'tea', type_='unique')
    # ### end Alembic commands ###
