"""Create users table

Revision ID: 1c8be238556a
Revises: 90eb6c84197d
Create Date: 2024-10-30 22:22:49.371923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c8be238556a'
down_revision: Union[str, None] = '90eb6c84197d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tea_country', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tea_country', type_='unique')
    # ### end Alembic commands ###
