"""add image field to Tea model

Revision ID: f38f05e4a6c1
Revises: da0435f3088d
Create Date: 2024-10-15 16:00:17.779629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f38f05e4a6c1'
down_revision: Union[str, None] = 'da0435f3088d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tea', sa.Column('image', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'tea', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tea', type_='unique')
    op.drop_column('tea', 'image')
    # ### end Alembic commands ###
